import React, { useState, useEffect } from 'react';
import api from '../../utils/api';
import toast from 'react-hot-toast';
import { Sparkles, ClipboardList, BookOpen, Save, RefreshCw, Layers, Plus } from 'lucide-react';

const TeacherAiTestGen = () => {
  const [batches, setBatches] = useState([]);
  const [loadingBatches, setLoadingBatches] = useState(true);

  // Form State
  const [batchId, setBatchId] = useState('');
  const [subject, setSubject] = useState('Physics');
  const [chapter, setChapter] = useState('');
  const [difficulty, setDifficulty] = useState('Medium');
  const [numQuestions, setNumQuestions] = useState(5);
  const [maxMarks, setMaxMarks] = useState(25);

  const [loadingGen, setLoadingGen] = useState(false);
  const [generatedQuestions, setGeneratedQuestions] = useState(null);
  const [testName, setTestName] = useState('');
  const [savingTest, setSavingTest] = useState(false);

  // Fetch batches to allow linking the test to a batch
  useEffect(() => {
    const fetchBatches = async () => {
      try {
        const res = await api.get('/teacher/batches');
        setBatches(res.data || []);
        if (res.data && res.data.length > 0) {
          setBatchId(res.data[0]._id);
        }
      } catch (error) {
        console.error('Failed to load teacher batches:', error);
      } finally {
        setLoadingBatches(false);
      }
    };
    fetchBatches();
  }, []);

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!chapter.trim()) {
      return toast.error('Please specify a chapter/topic');
    }

    setLoadingGen(true);
    setGeneratedQuestions(null);
    setTestName(`${subject} ${chapter} AI Test`);

    try {
      const res = await api.post('/ai/generate-test', {
        subject,
        chapter,
        difficulty,
        numQuestions,
        marks: maxMarks
      });
      setGeneratedQuestions(res.data.questions || []);
      toast.success('Test generated by AI successfully!');
    } catch (error) {
      console.error(error);
      toast.error('Failed to generate test. Please try again.');
    } finally {
      setLoadingGen(false);
    }
  };

  const handleSaveTest = async () => {
    if (!generatedQuestions || generatedQuestions.length === 0) return;
    if (!testName.trim()) return toast.error('Please enter a test name');
    if (!batchId) return toast.error('Please select an assigned batch');

    setSavingTest(true);
    try {
      const selectedBatchObj = batches.find(b => b._id === batchId);
      const testClass = selectedBatchObj ? selectedBatchObj.course?.name : 'XII Science';

      // Save to tests
      const res = await api.post('/teacher/tests', {
        name: testName,
        subject,
        class: testClass,
        batchId,
        date: new Date(),
        maxMarks
      });

      toast.success(`Test '${testName}' saved successfully to database!`);
      // Reset generated view
      setGeneratedQuestions(null);
      setChapter('');
    } catch (error) {
      console.error(error);
      toast.error(error.response?.data?.message || 'Failed to save test to database.');
    } finally {
      setSavingTest(false);
    }
  };

  const formatText = (text) => {
    if (!text) return '';
    return text.replace(/\$(.*?)\$/g, '<code class="px-1.5 py-0.5 bg-brand-secondary/80 border border-brand-border rounded font-mono text-brand-accent text-[11px]">$1</code>');
  };

  return (
    <div className="max-w-5xl mx-auto flex flex-col gap-8 text-left">
      {/* Title */}
      <div className="flex items-center gap-3 border-b border-brand-border pb-4">
        <div className="w-10 h-10 rounded-xl bg-brand-secondary flex items-center justify-center border border-brand-accent/20">
          <Sparkles className="h-5 w-5 text-brand-accent" />
        </div>
        <div>
          <h2 className="text-xl font-extrabold text-brand-accent">AI Test Generator</h2>
          <p className="text-xs text-text-muted">Auto-generate objective, subjective, or numerical tests based on coaching course parameters</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 items-start">
        {/* Left Side: Parameters Form */}
        <div className="lg:col-span-1">
          <form onSubmit={handleGenerate} className="glass rounded-2xl p-6 border border-brand-border flex flex-col gap-4">
            <h3 className="text-sm font-bold text-brand-accent uppercase tracking-wider">Configure Test Settings</h3>

            {/* Batch link */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold text-text-muted uppercase">Target Batch</label>
              {loadingBatches ? (
                <div className="h-9 bg-brand-secondary/40 rounded-xl animate-pulse" />
              ) : (
                <select
                  value={batchId}
                  onChange={(e) => setBatchId(e.target.value)}
                  className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent focus:border-brand-accent outline-none"
                  required
                >
                  {batches.map(b => (
                    <option key={b._id} value={b._id} className="bg-brand-primary text-brand-accent">{b.name} ({b.course?.name})</option>
                  ))}
                </select>
              )}
            </div>

            {/* Subject */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold text-text-muted uppercase">Subject</label>
              <select
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent focus:border-brand-accent outline-none"
              >
                {['Physics', 'Chemistry', 'Mathematics', 'Biology', 'Science'].map(sub => (
                  <option key={sub} value={sub} className="bg-brand-primary text-brand-accent">{sub}</option>
                ))}
              </select>
            </div>

            {/* Chapter */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold text-text-muted uppercase">Chapter / Topic</label>
              <input
                type="text"
                value={chapter}
                onChange={(e) => setChapter(e.target.value)}
                placeholder="e.g. Thermodynamics, Integration"
                className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent placeholder-text-muted focus:border-brand-accent outline-none"
                required
              />
            </div>

            {/* Grid for difficulty, counts, and marks */}
            <div className="grid grid-cols-2 gap-4">
              <div className="flex flex-col gap-1.5">
                <label className="text-[10px] font-bold text-text-muted uppercase">Difficulty</label>
                <select
                  value={difficulty}
                  onChange={(e) => setDifficulty(e.target.value)}
                  className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent focus:border-brand-accent outline-none"
                >
                  <option value="Easy" className="bg-brand-primary text-brand-accent">Easy (Board Prep)</option>
                  <option value="Medium" className="bg-brand-primary text-brand-accent">Medium (Mixed)</option>
                  <option value="Hard" className="bg-brand-primary text-brand-accent">Hard (Entrance Level)</option>
                </select>
              </div>

              <div className="flex flex-col gap-1.5">
                <label className="text-[10px] font-bold text-text-muted uppercase">Questions Count</label>
                <input
                  type="number"
                  min="1"
                  max="20"
                  value={numQuestions}
                  onChange={(e) => setNumQuestions(Number(e.target.value))}
                  className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent focus:border-brand-accent outline-none"
                  required
                />
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] font-bold text-text-muted uppercase">Total Test Marks</label>
              <input
                type="number"
                min="5"
                max="100"
                value={maxMarks}
                onChange={(e) => setMaxMarks(Number(e.target.value))}
                className="w-full bg-brand-secondary/60 border border-brand-border rounded-xl px-3 py-2 text-xs text-brand-accent focus:border-brand-accent outline-none"
                required
              />
            </div>

            <button
              type="submit"
              disabled={loadingGen}
              className="mt-2 w-full py-3 rounded-xl bg-brand-accent text-brand-primary font-bold text-xs hover:scale-[1.02] active:scale-[0.98] transition-all duration-200 flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {loadingGen ? (
                <div className="h-4 w-4 border-2 border-brand-primary border-t-transparent rounded-full animate-spin" />
              ) : (
                <>
                  Generate AI Test
                  <Sparkles className="h-4 w-4" />
                </>
              )}
            </button>
          </form>
        </div>

        {/* Right Side: Generated Test View */}
        <div className="lg:col-span-2">
          {loadingGen && (
            <div className="h-64 flex flex-col items-center justify-center text-center glass rounded-2xl border border-brand-border animate-pulse">
              <Sparkles className="h-10 w-10 text-brand-accent animate-spin mb-3" />
              <h3 className="text-sm font-bold text-brand-accent">Generating custom questions...</h3>
              <p className="text-xs text-text-muted mt-1">Formulating board exam patterns and answer solutions</p>
            </div>
          )}

          {!generatedQuestions && !loadingGen && (
            <div className="h-64 flex flex-col items-center justify-center text-center glass rounded-2xl border border-brand-border p-6">
              <BookOpen className="h-12 w-12 text-brand-accent/20 mb-3" />
              <h3 className="text-sm font-bold text-brand-accent">No active AI test</h3>
              <p className="text-xs text-text-muted max-w-sm mt-1">
                Configure target batch, subject, and marks on the left settings dashboard to generate examination sheets.
              </p>
            </div>
          )}

          {generatedQuestions && (
            <div className="flex flex-col gap-6 animate-fadeIn">
              {/* Test Save Banner */}
              <div className="glass rounded-2xl p-5 border border-brand-accent/20 bg-brand-accent/[0.02] flex flex-col sm:flex-row gap-4 items-center justify-between">
                <div className="flex-1 w-full text-left">
                  <label className="text-[10px] font-bold text-text-muted uppercase">Name of generated test</label>
                  <input
                    type="text"
                    value={testName}
                    onChange={(e) => setTestName(e.target.value)}
                    className="w-full bg-transparent border-b border-brand-border hover:border-brand-accent focus:border-brand-accent text-sm font-bold text-brand-accent outline-none py-1 mt-0.5 transition-colors"
                  />
                </div>
                <button
                  onClick={handleSaveTest}
                  disabled={savingTest}
                  className="w-full sm:w-auto px-5 py-2.5 bg-brand-accent text-brand-primary font-bold text-xs rounded-xl hover:scale-[1.02] active:scale-[0.98] transition-all flex items-center justify-center gap-1.5 disabled:opacity-50 shrink-0"
                >
                  <Save className="h-4 w-4" />
                  {savingTest ? 'Saving...' : 'Save & Link Test'}
                </button>
              </div>

              {/* Exam paper style rendering */}
              <div className="glass rounded-3xl p-8 border border-brand-border flex flex-col gap-6 shadow-md">
                <div className="text-center border-b border-brand-border pb-4">
                  <h2 className="font-display font-extrabold text-xl text-brand-accent tracking-wide">{testName}</h2>
                  <p className="text-xs text-text-muted mt-1">
                    Class level • Difficulty: {difficulty} • Marks: {maxMarks} • Count: {generatedQuestions.length}
                  </p>
                </div>

                <div className="flex flex-col gap-6">
                  {generatedQuestions.map((q, idx) => (
                    <div key={q.id || idx} className="text-left border-b border-brand-border pb-5 last:border-b-0">
                      <div className="flex justify-between items-start gap-2">
                        <h4 className="text-xs font-bold text-brand-accent leading-normal flex-1">
                          Q{idx + 1}. <span dangerouslySetInnerHTML={{ __html: formatText(q.text) }} />
                        </h4>
                        <span className="text-[10px] bg-brand-secondary/60 text-text-muted border border-brand-border px-2 py-0.5 rounded font-mono shrink-0">
                          {q.marks} Marks
                        </span>
                      </div>

                      {/* Options if MCQ */}
                      {q.type === 'MCQ' && q.options && q.options.length > 0 && (
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-3 pl-4">
                          {q.options.map((opt, oIdx) => (
                            <div key={oIdx} className="text-[11px] text-brand-accent-light p-2.5 rounded-xl bg-brand-secondary/60 border border-brand-border shadow-sm">
                              <span className="font-bold text-brand-accent mr-1">{String.fromCharCode(65 + oIdx)}.</span> {opt}
                            </div>
                          ))}
                        </div>
                      )}

                      {/* Solution preview */}
                      <div className="mt-3 p-3 bg-emerald-500/[0.03] dark:bg-emerald-500/[0.01] border border-emerald-500/20 dark:border-emerald-500/10 rounded-xl">
                        <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 block mb-1">Answer Key & Solution:</span>
                        <p className="text-[11px] text-brand-accent-light leading-relaxed" dangerouslySetInnerHTML={{ __html: formatText(q.solution) }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default TeacherAiTestGen;
